# Generated by Django 5.2.6 on 2025-09-30 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('author', models.CharField(max_length=200, verbose_name='Auteur')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Éditeur')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Année de publication')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Image de couverture')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité totale')),
                ('available_quantity', models.IntegerField(default=1, verbose_name='Quantité disponible')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BORROWED', 'Emprunté'), ('MAINTENANCE', 'En maintenance'), ('LOST', 'Perdu')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'emprunt")),
                ('due_date', models.DateTimeField(verbose_name='Date de retour prévue')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('status', models.CharField(choices=[('ACTIVE', 'En cours'), ('RETURNED', 'Retourné'), ('OVERDUE', 'En retard')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='website.book', verbose_name='Livre')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Emprunteur')),
                ('librarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_managed', to=settings.AUTH_USER_MODEL, verbose_name='Bibliothécaire')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('STUDENT', 'Étudiant'), ('TEACHER', 'Professeur'), ('STAFF', 'Personnel'), ('LIBRARIAN', 'Bibliothécaire')], default='STUDENT', max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
    ]
